# use http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# cache local Maven repo: http://docs.travis-ci.com/user/caching/
cache:
  directories:
  - $HOME/.m2/repository

language: java

# Use the 'true' command to avoid up-front dependency fetching, for faster builds
# See http://docs.travis-ci.com/user/languages/java/#Dependency-Management
install: /bin/true

# Travis build logs need to be small (aim for less than 4MB or 10,000 lines),
# so we try to minimise unwanted logging. However, Travis will kill the build
# if nothing is logged for 10 minutes (20 with travis_wait), so we do need
# some logging.

script: |
  mvn verify \
  --batch-mode \
  --settings .travis-settings.xml \
  -Dgwt.validateOnly \
  -Dappserver=wildfly8 \
  -DskipFuncTests \
  -Dmaven.test.redirectTestOutputToFile \
  -DstaticAnalysis | \
  egrep -v \
  '^(\[INFO\] Download|'\
  '\[WARNING\] Could not validate integrity of download from|'\
  '\[WARNING\] Checksum validation failed, no checksums available for)'

jdk:
  - oraclejdk8

matrix:
  fast_finish: true
