site_name: Zanata Server
docs_dir: docs
repo_name: GitHub
repo_url: http://www.github.com/zanata/zanata-server
theme: readthedocs
# theme_dir: For custom themes

pages:
- ['index.md', 'Home']
# Getting started
- ['user-guide/translator-guide.md', 'Getting Started', 'Translator Guide']
- ['user-guide/project-maintainer-guide.md', 'Getting Started', 'Project Maintainer Guide']
- ['user-guide/admin-guide.md', 'Getting Started', 'Zanata Admin Guide']
## Accounts
- ['user-guide/account/account-sign-up.md', 'Accounts', 'Create new account']
- ['user-guide/account/account-activate.md', 'Accounts', 'Activate account']
- ['user-guide/account/account-resend-activation.md', 'Accounts', 'Resend activation email']
- ['user-guide/account/account-settings.md', 'Accounts', 'Account settings']
- ['user-guide/account/user-profile.md', 'Accounts', 'User profile']
## Projects
- ['user-guide/projects/project-view.md', 'Projects', 'Project view']
- ['user-guide/projects/create-project.md', 'Projects', 'Creating a project']
- ['user-guide/projects/project-settings.md', 'Projects', 'Project settings']
- ['user-guide/projects/project-types.md', 'Projects', 'Project types']
- ['user-guide/projects/upload-strings.md', 'Projects', 'Upload strings']
## Versions
- ['user-guide/versions/version-view.md', 'Versions', 'Version view']
- ['user-guide/versions/create-version.md', 'Versions', 'Creating a version']
- ['user-guide/versions/version-settings.md', 'Versions', 'Version settings']
- ['user-guide/versions/request-to-join-group.md', 'Versions', 'Join a group']
- ['user-guide/versions/merge-translations.md', 'Versions', 'Merge translations']
- ['user-guide/versions/download-translations.md', 'Versions', 'Download translations']
## Languages
- ['user-guide/languages/language-team.md', 'Languages', 'Language team']
## Groups
- ['user-guide/groups/group-view.md', 'Groups', 'Group view']
- ['user-guide/groups/create-group.md', 'Groups', 'Creating a group']
- ['user-guide/groups/group-settings.md', 'Groups', 'Group settings']
## Editor
- ['user-guide/editor/keyboard-shortcuts.md', 'Editor', 'Keyboard shortcuts']
## API
- ['user-guide/api/api.md', 'API', 'Zanata API']
## Client
- ['user-guide/client/client.md', 'Zanata Client', 'Zanata client']
# Configuration
- ['configuration/installation.md', 'Configuration', 'Installation']
- ['configuration/authentication.md', 'Configuration', 'Authentication']
- ['configuration/document-storage-directory.md', 'Configuration', 'Document Storage Directory']
# Once pull request https://github.com/zanata/zanata-server/pull/633 is integrated, this can be uncommented
# - ['configuration/email.md', 'Configuration', 'Email']
- ['configuration/infinispan.md', 'Configuration', 'Caches']
- ['configuration/jms-messaging.md', 'Configuration', 'JMS Messaging']

- ['release-notes.md']

copyright: Copyright &copy; 2015, <a href="http//www.redhat.com">Red Hat</a>.
