site_name: Zanata Server
docs_dir: docs
repo_name: GitHub
repo_url: http://www.github.com/zanata/zanata-server
theme: readthedocs
# theme_dir: For custom themes

pages:
- ['index.md', 'Home']

# Configuration Guide
- ['configuration/installation.md', 'Configuration', 'Installation']
- ['configuration/authentication.md', 'Configuration', 'Authentication']
- ['configuration/document-storage-directory.md', 'Configuration', 'Document Storage Directory']
# Once pull request https://github.com/zanata/zanata-server/pull/633 is integrated, this can be uncommented
# - ['configuration/email.md', 'Configuration', 'Email']
- ['configuration/infinispan.md', 'Configuration', 'Caches']
- ['configuration/jms-messaging.md', 'Configuration', 'JMS Messaging']

# Release notes
- ['release-notes.md', 'Release Notes', 'Release Notes']

# User Guide
## Account
- ['user-guide/account/account-sign-up.md', 'User Guide', 'Create new account']
- ['user-guide/account/account-activate.md', 'User Guide', 'Activate account']
- ['user-guide/account/account-resend-activation.md', 'User Guide', 'Resend activation email']
- ['user-guide/account/account-settings.md', 'User Guide', 'Account settings']
## Project
- ['user-guide/projects/project-view.md', 'User Guide', 'The Project View']
- ['user-guide/projects/create-project.md', 'User Guide', 'Creating a Project']
- ['user-guide/projects/project-settings.md', 'User Guide', 'Project settings']
- ['user-guide/projects/project-types.md', 'User Guide', 'Project Types']
- ['user-guide/projects/upload-strings.md', 'User Guide', 'Upload Strings']
## Version
- ['user-guide/versions/version-view.md', 'User Guide', 'The Version View']
- ['user-guide/versions/create-version.md', 'User Guide', 'Creating a Version']
- ['user-guide/versions/version-settings.md', 'User Guide', 'Version settings']
- ['user-guide/versions/merge-translations.md', 'User Guide', 'Merge translations']
## General
- ['user-guide/joining-a-language-team.md', 'User Guide', 'Joining a Language team']
- ['user-guide/contributing-translations.md', 'User Guide', 'Contributing Translations']
- ['user-guide/user-profile.md', 'User Guide', 'User Profile Page']
## Editor
- ['user-guide/keyboard-shortcuts.md', 'User Guide', 'Keyboard Shortcuts']
## Client
- ['user-guide/client/client.md', 'User Guide', 'Zanata client']
- ['user-guide/client-command-hook.md', 'User Guide', 'Client Command Hook']


copyright: Copyright &copy; 2015, <a href="http//www.redhat.com">Red Hat</a>.
